remove strapi from development enviornment
Amythethird/Batta pull request #119
Opened 2022-08-10 07:47 UTC by acvm007

This uses the strapi instance at http://h2964058.stratoserver.net:5001
and removes strapi from docker pipeline

2022-08-10 14:57 UTC, mweiershaeuser commented
Wäre es nicht gut, trotzdem die Möglichkeit des lokalen Startens via Docker Compose beizubehalten und nur das genutzte Default-Backend auf das Backend des Servers abzuändern (nach dem Motto: du kannst das lokale zu Entwicklungszwecken nutzen, aber der Wartungsaufwand ist hoch und deshalb ist das nicht das Standard-Vorgehen)?

2022-08-12 10:37 UTC, JanKoll commented
Gute Idee, können wir so lachen 👍🏻

2022-08-14 11:26 UTC, mweiershaeuser requested changes
- [x] lokales Starten beibehalten

2022-08-14 17:05 UTC, Amythethird approved these changes

2022-08-14 17:07 UTC, Amythethird approved these changes

2022-08-14 17:08 UTC, Amythethird approved these changes

2022-08-14 19:43 UTC, mweiershaeuser commented
Bin nochmal über die Readme drüber, fand es jetzt so noch etwas verständlicher, ich hoffe das ist ok?

Just two more problems (ich weiß ich nerve :D)

- @acvm007 Wo haben wir denn jetzt eigentlich die richtige .env Datei für den Docker-Ordner? Ich habe bei mir eine, wo keine BASE_URL drin ist 😂
- Je nach Browser schlägt halt trotzdem der Request an das gehostete Strato Backend fehl, weil CORS das für unverschlüsselte Verbindungen blockiert. @JanKoll Können wir das Backend vielleicht TLS-sichern (Let's Encrypt)?

Da das aber mit den Änderungen hier nicht direkt was zu tun hat, kriegst du natürlich schonmal das Approval.

2022-08-14 19:44 UTC, mweiershaeuser approved these changes

2022-08-14 19:47 UTC, mweiershaeuser commented
![grafik](https://user-images.githubusercontent.com/51531071/184552454-33209b37-be1c-4dfa-bae8-6839976ec8ed.png)

@JanKoll Bzw. Strapi scheint schon gewissenmaßen gesichert zu sein, aber offenbar nicht funktionierend.

2022-08-14 19:48 UTC, acvm007 commented
> Bin nochmal über die Readme drüber, fand es jetzt so noch etwas verständlicher, ich hoffe das ist ok?
> 
> Just two more problems (ich weiß ich nerve :D)
> 
>     * @acvm007 Wo haben wir denn jetzt eigentlich die richtige .env Datei für den Docker-Ordner? Ich habe bei mir eine, wo keine BASE_URL drin ist 😂
> 
>     * Je nach Browser schlägt halt trotzdem der Request an das gehostete Strato Backend fehl, weil CORS das für unverschlüsselte Verbindungen blockiert. @JanKoll Können wir das Backend vielleicht TLS-sichern (Let's Encrypt)?
> 
> 
> Da das aber mit den Änderungen hier nicht direkt was zu tun hat, kriegst du natürlich schonmal das Approval.

Hab Strapi zu treafik services hinzugfefuegt.
Inhalt der .env fuers Docker:

ENV=development
BASE_URL=http://h2964058.stratoserver.net:5001
#BASE_URL=http://strapi.localhost

2022-08-16 11:08 UTC, merged